apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: code-server-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - code-{{ .Values.user }}.scrape.center
      secretName: tls-wildcard-scrape-center
  rules:
    - host: code-{{ .Values.user }}.scrape.center
      http:
        paths:
          - backend:
              serviceName: code-server-{{ .Values.user }}
              servicePort: 80
            path: /
