kind: Service
apiVersion: v1
metadata:
  name: code-server-{{ .Values.user }}
spec:
  type: ClusterIP
  selector:
    app: code-server-{{ .Values.user }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: code-server-{{ .Values.user }}

