kind: Service
apiVersion: v1
metadata:
  name: code-server-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  {{- if empty .Values.loadBalancerSourceRanges }}
  {{- fail "A valid .Values.loadBalancerSourceRanges entry required!" }}
  {{- end }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.loadBalancerSourceRanges | nindent 2 }}
  selector:
    app: code-server-{{ .Values.user }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: code-server
    name: code-server-{{ .Values.user }}

